# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: "3.4"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
    hostname: mongo

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq

  catalog-api-service:
    image: iphonemax-catalog-api:v1.0.1
    build:
      context: services/iphonemax-catalog-api-service
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - mongo
    ports:
      - 5000:5000
      - 5001:5001
    hostname: catalog

  cart-service:
    image: iphonemax-cart-api:v2.0.0
    build:
      context: services/iphonemax-cart-api-service
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - mongo
    ports:
      - 5004:5004
      - 5005:5005
    hostname: cart

  frontend-service:
    image: iphonemax-frontend:v7.0.0
    build:
      context: services/iphonemax-frontend-service
      dockerfile: Dockerfile
    environment:
      - "CATALOG_ITEMS_API_URL=http://localhost:5000"
      - "CART_ITEMS_API_URL=http://localhost:5004"
      - "RABBITMQ_URL=http://localhost:5672"
    ports:
      - 3000:80
    depends_on:
      - catalog-api-service
      - cart-service
    hostname: frontend

volumes:
  mongodbdata:
  rabbitmqdata:
