# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: "3.4"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
    hostname: mongo

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq

  catalog-api-service:
    image: iphonemax-catalog-api
    build:
      context: services/iphonemax-catalog-api-service
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - mongo
    ports:
      - 5001:5001
      - 5000:5000
    hostname: catalog

  cart-service:
    image: iphonemax-cart-api
    build:
      context: services/iphonemax-cart-service
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - mongo
    ports:
      - 5005:5005
      - 5004:5004
    hostname: cart

  frontend-service:
    image: iphonemax-frontend
    build:
      context: services/iphonemax-frontend-service
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:80
    depends_on:
      - catalog-api-service
      - cart-service
    hostname: frontend

volumes:
  mongodbdata:
  rabbitmqdata:
