apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-10-29T04:43:36Z"
  generateName: iphonemax-frontend-c6dcd68b6-
  labels:
    app: iphonemax-frontend
    pod-template-hash: c6dcd68b6
  name: iphonemax-frontend-c6dcd68b6-nncqq
  namespace: default
  ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: iphonemax-frontend-c6dcd68b6
      uid: 3ceef761-0b42-4fd0-a03e-6c7640c8acfb
  resourceVersion: "10180"
  uid: 0c5a02d8-4212-4315-86e6-fa307414289c
spec:
  containers:
    - image: ecomfrontend:latest
      imagePullPolicy: IfNotPresent
      name: ecomfrontend
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-mgpfn
          readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: kind-control-plane
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
  volumes:
    - name: kube-api-access-mgpfn
      projected:
        defaultMode: 420
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              items:
                - key: ca.crt
                  path: ca.crt
              name: kube-root-ca.crt
          - downwardAPI:
              items:
                - fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
                  path: namespace
status:
  conditions:
    - lastProbeTime: null
      lastTransitionTime: "2022-10-29T04:43:36Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2022-10-29T04:43:36Z"
      message: "containers with unready status: [ecomfrontend]"
      reason: ContainersNotReady
      status: "False"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2022-10-29T04:43:36Z"
      message: "containers with unready status: [ecomfrontend]"
      reason: ContainersNotReady
      status: "False"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2022-10-29T04:43:36Z"
      status: "True"
      type: PodScheduled
  containerStatuses:
    - image: ecomfrontend:latest
      imageID: ""
      lastState: {}
      name: ecomfrontend
      ready: false
      restartCount: 0
      started: false
      state:
        waiting:
          message: Back-off pulling image "ecomfrontend:latest"
          reason: ImagePullBackOff
  hostIP: 172.18.0.2
  phase: Pending
  podIP: 10.244.0.17
  podIPs:
    - ip: 10.244.0.17
  qosClass: BestEffort
  startTime: "2022-10-29T04:43:36Z"
