apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-api-deployment
  labels:
    app: cart-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-api
  template:
    metadata:
      labels:
        app: cart-api
    spec:
      containers:
        - name: cart-api
          image: sajidhmcr.azurecr.io/iphonemax-cart-api:v1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 5005
          env:
            - name: RABBIT_HOST
              value: "mu-rabbit-rabbitmq.default.svc.cluster.local"
            - name: RABBIT_PORT
              value: "5672"
            - name: RABBIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbit-secret
                  key: RABBIT_USERNAME
            - name: RABBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbit-secret
                  key: RABBIT_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: cart-api-service
  labels:
    app: cart-api
spec:
  selector:
    app: cart-api
  ports:
    - protocol: TCP
      name: http
      port: 5005
      targetPort: 5005
