apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: sajidhmcr.azurecr.io/iphonemax-frontend:v1.0.3
          resources:
            limits:
              memory: 1024Mi
              cpu: "1"
            requests:
              memory: 512Mi
              cpu: "0.2"
          ports:
            - containerPort: 3000
          env:
            - name: CATALOG_SERVICE_URL
              value: "http://catalog-api-service:5001"
            - name: CART_SERVICE_URL
              value: "http://cart-api-service:5005"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    run: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
