# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
    hostname: mongo

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq

  catalog:
    image: ecomcatalogservice
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      - rabbitmq
      - mongo
    ports:
      - 5001:5001
    hostname: catalog

volumes:
  mongodbdata:
  rabbitmqdata:
