apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-api-deployment
  labels:
    app: cart-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-api
  template:
    metadata:
      labels:
        app: cart-api
    spec:
      containers:
        - name: cart-api
          image: docker.io/library/k8s-cart-api
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5005
          env:
            - name: RABBIT_HOST
              value: "mu-rabbit-rabbitmq.default.svc.cluster.local"
            - name: RABBIT_PORT
              value: "5672"
            - name: RABBIT_USERNAME
              value: guest
              # valueFrom:
              #   secretKeyRef:
              #     name: rabbitmq-publisher
              #     key: RABBIT_USERNAME
            - name: RABBIT_PASSWORD
              value: guest
              # valueFrom:
              #   secretKeyRef:
              #     name: rabbitmq-publisher
              #     key: RABBIT_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: cart-api-service
spec:
  type: NodePort
  selector:
    app: cart-api
  ports:
    - protocol: TCP
      port: 5005
      targetPort: 5005
      nodePort: 32000
