apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api-deployment
  labels:
    app: catalog-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-api
  template:
    metadata:
      labels:
        app: catalog-api
    spec:
      containers:
        - name: catalog-api
          image: docker.io/library/k8s-catalog-api
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 256Mi
              cpu: "1"
            requests:
              memory: 128Mi
              cpu: "0.2"
          ports:
            - containerPort: 5001
              name: htps
              protocol: UDP
            - containerPort: 5000
              name: hp
              protocol: UDP
          env:
            - name: RABBIT_HOST
              value: "mu-rabbit-rabbitmq.default.svc.cluster.local"
            - name: RABBIT_PORT
              value: "5672"
            - name: RABBIT_USERNAME
              value: guest
              # valueFrom:
              #   secretKeyRef:
              #     name: rabbitmq-publisher
              #     key: RABBIT_USERNAME
            - name: RABBIT_PASSWORD
              value: guest
              # valueFrom:
              #   secretKeyRef:
              #     name: rabbitmq-publisher
              #     key: RABBIT_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-api-service
spec:
  type: NodePort
  selector:
    app: catalog-api
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 31000
